### ISSUE TITLE
Upgrade Zola Ember (3.28) & Node 16 Some More

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#1098]
# This issue is closed when Ember is version 3.28 and the app builds in Netlify for Node 16

**Comment by TylerMatteo** [comment]
Yeah, I'm not crazy about us essentially taking on supporting the pieces of that abandoned addon that we still use but so long as that's the case, I don't have a problem with it being in labs-shared.

**Comment by TylerMatteo** [comment]
@allthesignals Can you give a tldr of which packages you've moved into labs-shared so far? I see labs-ui, labs-ember-search, and ember-mapbox-composer in there so far, if I'm reading it correctly. Are you planning to move [carto-promises-utility](https://github.com/NYCPlanning/cartobox-promises-utility) into it too? Just wondering because I think we'll want to move all of our ember addons into this eventually, but some of that can be follow up work for the rest of the team.

I'll find some time to set up a repo in our GH org for this but for now, keep doing what you're doing.

**Comment by TylerMatteo** [comment]
Agree with everything RE ember-needs-async, it's a pretty small compromise in the grand scheme of things. I'll work on getting that repo set up this asap, should have something for you by end of the week at the latest.
