### ISSUE TITLE
Feedback loop, form, for the public

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#208]
We discussed needing a way to have the public e-mail a ZoLa distro-list, a Github issue, or something else.

**Comment by chriswhong** [comment]
It would be great to wire this up so it goes to a distro list AND creates a github issue from `zola-bot` or something.  User should be made aware that their comment will be public.

**Comment by andycochran** [comment]
Quickest path, let's do it the same way as [Community Profiles](https://communityprofiles.planning.nyc.gov/). Bottom of the About page.

**Comment by andycochran** [comment]
So that the feedback loop is more visible, I think this should be done along with #225.

**Comment by allthesignals** [comment]
I was thinking about something like Intercom: https://www.intercom.com/. Maybe helpdesk questions can also be handled through intercom? These could also be feedback submissions.

![image](https://user-images.githubusercontent.com/5004319/31239587-a24ae7ea-a9cb-11e7-8422-d63564836386.png)

I've seen this used across many sites, it's very effective from a user perspective...

**Comment by andycochran** [comment]
I think help desk tools are great. But this issue is meant to provide UX feedback about ZoLa as a tool — e.g. "How can the tool be better?" Help desk tools like Intercom work best when there's a dedicated team monitoring communications. I'm not sure that will be the case, as Planning Labs will be focusing on other projects. 

A help desk tool might also set up the expectation that DCP's Zoning Help Desk is monitoring the tool and encourage zoning-specific questions, not UX feedback. 

Perhaps we need two explicit paths for user feedback: 

1. For UX feedback, add a GitHub Issue or contact Planning Labs (Twitter?) 
2. For zoning Qs, contact the Zoning Help Desk (via email? Intercom?)

/cc @fruchala

**Comment by allthesignals** [comment]
I think I was trying to say that the dedicated team would be the Helpdesk volunteers. It's the same thing, just not over the phone. UX feedback would be handled through something like Intercom, new issues are opened as a reply.

**Comment by andycochran** [comment]
👍 If the Zoning Help Desk volunteers want this.

**Comment by andycochran** [comment]
After chatting offline, the agreed-upon solution is to explicitly state the two feedback channels: 

1. To let us know how this app could be better, [add a GitHub Issue](https://github.com/NYCPlanning/labs-zola/issues/) or Tweet [#ReimagineZoLa](https://twitter.com/hashtag/ReimagineZoLa?src=hash) to [@NYCPlanningLabs](https://twitter.com/nycplanninglabs). 
2. To ask a general zoning question, first check the [Zoning Help Desk FAQ](https://www1.nyc.gov/site/planning/zoning/zoning-faq.page). If your question is not answered in the FAQ, then call 212-720-3291 during business hours (8:30AM–5:30PM, Monday–Friday, closed on legal holidays), leave a detailed message, and a zoning specialist will get back to you within two business days. Or fill out the [Zoning Information Inquiry Form](https://www1.nyc.gov/site/planning/zoning/zoning-inquiry.page). Please have your block and lot information available when you contact the Help Desk.

^ This mirrors the process layed out on [DCP's contact page](https://www1.nyc.gov/site/planning/about/contact-us.page)
