### ISSUE TITLE
Supporting Layers Need External Links

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#288]
> These supporting layers need to link to additional info. It’s fine if they do it like special purpose districts (old ZOLA has this)
> - [ ]  SPD
> - [ ]  IH
> - [ ]  Transit Zone
> - [ ]  Fresh Zone
> - [ ]  WAP
> - [ ]  Coastal zone
> - [ ]  LH zone
> - [x]  Historic Districts #328
> - [ ] (add link to additional info for the special districts) 
>
>  -@fruchala

**Comment by allthesignals** [comment]
Related #31

**Comment by andycochran** [comment]
There are two ways to solve this… 

1. Link to the additional info from the lot view, for lots that are within supporting layers' features. 
2. Each of these is routable. The page content is the same as the `titleTooltip` followed by a link to the additional info. Just like Zoning Districts, they could also have a "Fit map to all" button.

**Comment by andycochran** [comment]
Related to #309. Commercial Overlays are listed in the lot view and link to more info. Supporting Layers could be listed the same way (1 above). And, if Supporting Layers are made routable (2 above) Commercial Overlays could be done the same way.

**Comment by allthesignals** [comment]
>Each of these is routable. The page content is the same as the titleTooltip followed by a link to the additional info. Just like Zoning Districts, they could also have a "Fit map to all" button.

@andycochran I don't follow what this means. If they're all routable they should already have page content? 

There's a lot still going on in this issue. It's not clear what I need to actually build. Who's the decision-maker on what's best to build? Like I mentioned in #31, I'm just going to pick a few random layers and build something, and that's what we get to because there's not a consensus on what this feature needs to actually be.

**Comment by fruchala** [comment]
I am around today to discuss what this should be.

**Comment by andycochran** [comment]
Edited my comment above. We can chat about this IRL if it's not clear. Sorry for the confusion.

**Comment by andycochran** [comment]
@fruchala Could you provide the external URLs to which all of these should links?

**Comment by fruchala** [comment]
working now...

**Comment by fruchala** [comment]
SPD
http://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts.page

 IH
http://www1.nyc.gov/site/planning/zoning/districts-tools/inclusionary-housing.page

Transit Zone
no link available. 

Fresh Zone
http://www1.nyc.gov/site/planning/zoning/districts-tools/fresh-food-stores.page

FLOOD ZONE (when there)
http://www1.nyc.gov/site/planning/zoning/districts-tools/flood-text.page

 WAP
http://www1.nyc.gov/site/planning/zoning/districts-tools/waterfront-zoning.page#waterfront_access_plan

Coastal zone
http://www1.nyc.gov/site/planning/applicants/wrp/wrpcoastalmaps.page

Lower Density Growth Management
http://www1.nyc.gov/site/planning/zoning/districts-tools/lower-density-growth-mngmt.page

 LH zone
http://www1.nyc.gov/site/planning/zoning/glossary.page#limited_height_district

 Historic Districts #328
 (add link to additional info for the special districts)

**Comment by allthesignals** [comment]
Linking to additional info from the lot view if that lot's geometric representation intersects with any of those layers' geometries. 

Since transit zone doesn't have a link, how should it be represented in the lot view?

**Comment by fruchala** [comment]
Link it to the glossary. We’ll add something to it.

http://www1.nyc.gov/site/planning/zoning/glossary.page


Sent from my iPhone

On Oct 19, 2017, at 5:55 PM, Matt Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:


Linking to additional info from the lot view if that lot's geometric representation intersects with any of those layers' geometries.

Since transit zone doesn't have a link, how should it be represented in the lot view?

**Comment by andycochran** [comment]
http://www1.nyc.gov/site/planning/zoning/glossary.page#transit_zone

**Comment by allthesignals** [comment]
Which layer is the flood zone layer?

**Comment by allthesignals** [comment]
I've push up a commit that links to everything mentioned, if an intersection occurs. Please check it out on PR #329 @andycochran thanks.

**Comment by fruchala** [comment]
I’ve sent them previously.

https://nycplanning.slack.com/archives/C6VU3RNCF/p1507243468000278

Sent from my iPhone

On Oct 19, 2017, at 6:03 PM, Matt Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:


Which layer is the flood zone layer?

**Comment by allthesignals** [comment]
Thx. Copying @fruchala's message here:
>three other comments from people...
>1) because of the line weight / color of the zoning boundaries and zoning district names, they are getting lost when the tax lots with land use colors are turned on. you could still see the zoning with the land uses on in old Zola. can we address? 
>2) there's something weird going on with the commercial overlay button. it keeps turning off when we switch tabs on browswers.
>3) there's two layers that we should add for the flood zone (this was an oversight on my part). They are included in the DCP flood hazard mapper and their info is here: http://dcp.maps.arcgis.com/home/item.html?id=1e56cf3d576849d1a6936f9cdcd3511d#overview
http://dcp.maps.arcgis.com/home/item.html?id=d85a205d9a284b449741cb397c0ee4b7

**Comment by fruchala** [comment]
Cool. It wouldn’t let me just copy the links with my phone. Thanks!

Sent from my iPhone

On Oct 19, 2017, at 6:26 PM, Matt Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:


Thx. Copying @fruchala<https://github.com/fruchala>'s message here:

three other comments from people...

  1.  because of the line weight / color of the zoning boundaries and zoning district names, they are getting lost when the tax lots with land use colors are turned on. you could still see the zoning with the land uses on in old Zola. can we address?
  2.  there's something weird going on with the commercial overlay button. it keeps turning off when we switch tabs on browswers.
  3.  there's two layers that we should add for the flood zone (this was an oversight on my part). They are included in the DCP flood hazard mapper and their info is here: http://dcp.maps.arcgis.com/home/item.html?id=1e56cf3d576849d1a6936f9cdcd3511d#overview
http://dcp.maps.arcgis.com/home/item.html?id=d85a205d9a284b449741cb397c0ee4b7
