### ISSUE TITLE
Add Mandatory and Voluntary Housing Designated Layers in Intersecting Map Layers

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#341]
It would be good for people to be able to see at a glance how their lot is affected by particular supporting zoning. It's more important than the others.

In this issue, we should also refactor the way intersecting layers are handled. Currently, they are not tasks and there's no way to round up the status of all promises. 

Maybe this should be done in the route view? It will slow the overall load time of the intersecting layers calculations.

**Comment by allthesignals** [comment]
@andycochran historic district is provided by the mappluto data, not part of the intersection calculation. So it's hard get a "none found logic" working.

**Comment by andycochran** [comment]
Hmm… Perhaps the mappluto data (e.g. historic district) shouldn't be listed under "Intersecting Map Layers." 

However, it _is_ also a map layer, so it makes sense there. We _could_ get the tax lot relationship from there instead of from pluto, but pluto might be more accurate and will definitely be faster. 

(Should this be a separate issue? Users sees "N/A" if no intersecting map layers.)

**Comment by allthesignals** [comment]
@andycochran hmm can you check my PR? Users should see "none found" if there are no intersecting layers. It also considers the presence of historic districts through the pluto data.
