### ISSUE TITLE
Mobile Version - Lot clicking

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#369]
The ability to click individual lots, which is very helpful, is not working in the mobile version.

**Comment by andycochran** [comment]
@chriswhong This was the bug with Draw? Should be irrelevant now?

**Comment by andycochran** [comment]
Or, could this be iOS trying to be smart about the hover state (the first touch event firing a hover instead of a click)?

**Comment by andycochran** [comment]
Did a little testing… It looks like this is a Mapbox GL hover issue. The first time you interact with the map via touch device, the first tap event triggers a hover, not a click. Subsequent taps seem to work as clicks tho. @chriswhong, can we force Mapbox GL touch events to always trigger a click instead of a hover?

**Comment by chriswhong** [comment]
This is expected behavior, we will not address it right now.
