### ISSUE TITLE
Add Historic Aerial Raster Layers

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#441]
Request to add in older aerial photos (1924, 1996, etc) into ZoLa. were not available in previous version

**Comment by chriswhong** [comment]
Various historic imagery layers are published by DoITT GIS here: https://maps.nyc.gov/tiles/

However, the current aerials are proxied through a small node service (originally setup for the capital planning platform and used in ZoLa), I believe this was due to CORS issues with the published services.

**Comment by chriswhong** [comment]
Prioritize: 1924, 1951, 1996

Implied in this issue is ensuring that the user cannot turn on more than one raster layer at a time, so turning on an aerials layer should turn off all others.

If possible without too much more effort, add all available.    
Idea: to avoid the layer palette getting very long, add a dropdown to the Aerials layer to choose the year.

**Comment by allthesignals** [comment]
Layers and endpoints:
 - [ ] 1924 
 - [ ] 1951 
 - [ ] 1996

**Comment by allthesignals** [comment]
@chriswhong 

> However, the current aerials are proxied through a small node service (originally setup for the capital planning platform and used in ZoLa), I believe this was due to CORS issues with the published services.

Is this a service we maintain? Is it on Github somewhere w/ a readme? If the layers don't support CORS, we'll have to use a proxy.

**Comment by chriswhong** [comment]
@allthesignals this is not the case anymore, it was about a year ago, but the DoITT tiles are now usable directly as they are published.

**Comment by allthesignals** [comment]
How should this be styled? @chriswhong @andycochran 
<img width="321" alt="screen shot 2018-03-12 at 2 37 00 pm" src="https://user-images.githubusercontent.com/5004319/37302771-e5338c02-2602-11e8-8c14-06a93990b4db.png">
<img width="163" alt="screen shot 2018-03-12 at 2 36 54 pm" src="https://user-images.githubusercontent.com/5004319/37302772-e544e736-2602-11e8-9db7-cf408c7a24c9.png">
<img width="169" alt="screen shot 2018-03-12 at 2 36 45 pm" src="https://user-images.githubusercontent.com/5004319/37302773-e550b6e2-2602-11e8-8373-be6f19df76e1.png">
<img width="331" alt="screen shot 2018-03-12 at 2 36 39 pm" src="https://user-images.githubusercontent.com/5004319/37302774-e55dd0f2-2602-11e8-8b13-1dd0888c7374.png">

**Comment by chriswhong** [comment]
Recommend that this appear as a custom control underneath the layergroup control.
- "Aerials" will appear as an item beneath "Basemaps" in the layer palette.
- When toggled on, the list of available years will appear in a smaller font (as seen in the landmarks layer and others) with radio buttons next to each entry.
- 2016 will be on by default, user can choose other years.
- bonus: allow for query params to persist the selected aerials year.

**Comment by andycochran** [comment]
Agree with Chris. Aerials should have the switch (same level as Subway/Bldg Footprints/3D). The list of years should be radio buttons. And definitely qps for the specific aerial tile set so it can be shared.
