### ISSUE TITLE
Close box not visible on Safari

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#454]
#### What should happen:
See close "x" to close right panel

#### What happened instead:
Close x was not visible

#### Browser(s) and Device(s) observed on:
iPad 10inch

**Comment by andycochran** [comment]
Seems to work portrait but not landscape. 

![image](https://user-images.githubusercontent.com/409279/34125890-c0d252ce-e405-11e7-836f-2895f4a36ddb.png)

![image](https://user-images.githubusercontent.com/409279/34125874-b6886e20-e405-11e7-9a21-183968c6c4fa.png)

**Comment by andycochran** [comment]
And seems to be a bigger issue than the close button. The whole map is missing.

**Comment by andycochran** [comment]
I've got a fix for the hidden map, explicitly setting the height of  the `.navigation-area`. However the missing `. close-button` is a bit more complicated. 

Here's the gist of what's going on: 

The `. close-button` (which has `position:fixed`) is a child of `. content-area` (which has `overflow-x:hidden`). An element with fixed position should ignore its parent's overflow. This is the case for every browser except Safari, on which  the child honors the parent's overflow. So this bug is present not just on iPads, but also on desktop Safari.  [This write-up](https://miketaylr.com/posts/2015/06/position-fixed-overflow-hidden.html) describes the problem: a combination of `position:relative` and `z-index` on the parent. 

I'll dig further into a fix. Maybe I can avoid one of those declarations on the parent.
