### ISSUE TITLE
Add ability to search by block

### ISSUE THREAD

**Issue by jamesmlloyd** [NYCPlanning/labs-zola#502]
#### Description
The previous ZoLa had an ability to search by tax block. This was very helpful, as users could search by blocks when lot numbers are unavailable. It would be helpful if this were added as a feature.

**Comment by chriswhong** [comment]
This is not adding blocks as search result type, but would mean adding them to the bbl entry form, allowing the user click submit with only borough and block selected.  

On submission the map would zoom to a block centroid, but not change the route.

**Comment by chriswhong** [comment]
related to #479

**Comment by allthesignals** [comment]
> This is not adding blocks as search result type, but would mean adding them to the bbl entry form, allowing the user click submit with only borough and block selected.

Hmm not sure I follow what you mean by this... we want users to be able to search for a boro and block and zoom to the extent of that block if it's found, but provide feedback if nothing is found? What should this look like?

**Comment by allthesignals** [comment]
Error message is in here: 
![image](https://user-images.githubusercontent.com/5004319/37720105-ed323056-2cfc-11e8-8313-11713a7a5335.png)

**Comment by chriswhong** [comment]
Can I suggest that we validate the input with each keypress and disable the button if a valid block and lot is not selected?

It requires more API calls but I think it might be a better UX.

We should also make the button read "Go to block", if only borough and block are specified.

I suggest the following updates:

Disable the button unless a validated borough and block are entered.
Button should read "Go to Block" if only borough and block are selected, and "Go to Lot" only if all three are specified.
Validate all entries, instead of making the user click the button to figure out if that lot exists, we can check constantly and if there is no result, gray out the button and show and error message "Block 342 in Queens does not exist"

**Comment by allthesignals** [comment]
Yes I like that - can we get @andycochran's input too? I was hoping to get a little more clarity on this issue when I was working on it. We should start a new issue probably at this point.

**Comment by andycochran** [comment]
I like Chris's suggestion. Tho, I think the button's texts should read: 

- View Lot
- Zoom to Block

^ This will make it more clear than one takes you to lot details and the other simply zooms the map.
