### ISSUE TITLE
Special Madison Ave Preservation District link goes to Citywide Page instead of Manhattan page

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#561]
Nicole Vargas (Zoning Div):

The link for the Special Madison Ave Preservation District directs user to Citywide Special District Page instead of Manhattan Special District Page.

currently links to **Citywide** here: https://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-citywide.page

should link to **Manhattan** here: https://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-manhattan.page#madison

**Comment by chriswhong** [comment]
All special purpose districts link to the citywide page, as we have no way of knowing what to link to from the attributes.

I think the only way we can fix this is if we add attributes to the dataset that will enable link-building.  Because the DCP website has `name` attributes on the headers on the special purpose district pages, we could link to them.  For example, here is the link to the battery park special district:

https://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-manhattan.page#battery_park

In order to compose a link like this, we would need a `borough` and a `districtname` field added to the dataset.

**Comment by allthesignals** [comment]
We should communicate with the web team on this so we can establish conventions that make URL guessability more sustainable. @CeciliaCY, sorry to ping, but any thoughts? If we could take option #2, that would be idea, because then we could have a reliable naming convention that requires no additional crosswalks (which would have to also be updated accordingly).
