### ISSUE TITLE
New staging: BBL search pre-populates with zero

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#684]
This isn't the case in production. The production site shows blank cells for block and lot. Screenshot: ![image](https://user-images.githubusercontent.com/13967925/47581691-29e73800-d920-11e8-8b06-3b93668ede13.png)

**Comment by andycochran** [comment]
This is happening because of [lines 93-94 in `/controllers/application.js`](https://github.com/NYCPlanning/labs-zola/blob/develop/app/controllers/application.js#L93-L94). These arguments are set to empty strings [in the addon](https://github.com/NYCPlanning/labs-ember-search/blob/master/addon/components/labs-bbl-lookup.js#L25-L29). If you delete the consuming app's zero from the lot field in the BBL lookup form and try to submit it (e.g. Queens block 100), you get a couple errors, the key one being: 

```
Error while processing route: lot Assertion Failed: `id` passed to `findRecord()` has to be non-empty string or number Error: Assertion Failed: `id` passed to `findRecord()` has to be non-empty string or number
```

@allthesignals I wonder if this could be a decorator issue (similar to what we discovered with PFF + Composer) since the addon uses `default class` syntax with decorators but the consuming app uses the good old fashioned syntax.

**Comment by allthesignals** [comment]
@andycochran it might be but I think the nature of the error would be totally different.

If you have some time can you switch that addon back to classic syntax? Shouldn't take long as there are only 2 component (I think).

**Comment by hannahkates** [comment]
@andycochran, @allthesignals. Is anyone actively working on this right now? Moving back to "to do"

**Comment by allthesignals** [comment]
> @andycochran it might be but I think the nature of the error would be totally different.
> 
> If you have some time can you switch that addon back to classic syntax? Shouldn't take long as there are only 2 component (I think).

^ @hannahkates I just did this, so let me see if it helps.

**Comment by allthesignals** [comment]
If it needs to happen for this sprint it should def go in to do
