### ISSUE TITLE
Revise ordering of layers to make it easier to click on tax lots and points

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#696]
Desired order of layering (starting with topmost layer):
- Points (e-designations and landmarks)
- Tax lots
- Everything else in descending order according to the legend menu

----

Minor issue I’ve encountered often: Whenever I try to select a specific tax lot with the mouse, it always selects the underlying zoning district or commercial overlay. 
 
For example, I tried to click for lot 31 (below, indicated by red circle) several times, but only C2-4 info appears. 
 
![image001](https://user-images.githubusercontent.com/1833820/48563562-a7b8b680-e8c2-11e8-8f1a-dbac30329c66.jpg)

**Comment by andycochran** [comment]
Looks like the problem here is that since Commercial Overlays are on by default, and since they're above lots, they prevent you from clicking on lots. A few solutions come to mind: 

1. 👍 Make the COs layer group turned off by default, as other non-underlying zoning like SPDs are. 

2. 👎 Make the COs non-clickable when zoomed in close. This could be frustrating if you're trying to click a CO while zoomed in too far, and would require choosing a specific zoom level that'd have edge cases. 

3. 👎 Move tax lots above COs. You'd have to turn off tax lots to click a CO.

**Comment by hannahkates** [comment]
Looking into this again -- It seems like the described behavior only happens on staging. On production, you can't click on the COs until you turn off tax lots. I think the behavior on production is preferable.

**Comment by allthesignals** [comment]
Sounds like the solution is to turn off CO by default?
@andycochran

**Comment by andycochran** [comment]
In the last meeting with the client, we discussed rethinking the order of all layers, and it was decided that — tho we don't know the order of them all yet — tax lots should ALWAYS be the topmost layer. That should resolve this issue.

**Comment by allthesignals** [comment]
Hmmm,  I think we gotta look into how mapbox-gl deals within implicit ordering. I understand that visual order is honored by the implicit position in which layers are added... but I'm not sure that even applies to events in mapbox-gl.

**Comment by allthesignals** [comment]
My current approach is to traverse the _layers_ array, which is ordered reliably, and search the mouse event's intersecting features for the ID. When it finds something, it escapes the loop.

**Comment by chriswhong** [comment]
We just need to make sure tax lots gets added last of all of the layergroups.  I'd test it out to see if it can be as simple as mutating the array of layergroups that comes back from the layers api before anything else in ember gets their hands on it.
