### ISSUE TITLE
Add ability to clear filters

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#72]
Reset the layers to the app default.

**Comment by chriswhong** [comment]
This already happens when the user clicks 'ZoLa' in the header, do we want to add a button?

@andycochran any thoughts on moving the search bar to the map (I think it controls the map directly, and doesn't really have much to do with the layer selector) and adding a reset button to the top of the layer selector?

**Comment by andycochran** [comment]
I think this issue was created before the ZoLa heading behaved this way. I'm not sure we need to create a button for this explicit purpose. But if we do, does the ZoLa heading need to be a link? I'm okay with closing this — the ability is there and users haven't asked for a button. 

:+1: to moving search. But let's make that a separate issue.

**Comment by allthesignals** [comment]
@andycochran @chriswhong is this closed? What's the design for this?

**Comment by chriswhong** [comment]
I guess we are still debating.  I am in favor of a "Reset Layers" button, and think the "Click the word ZoLa" thing is awkward.

**Comment by hannahkates** [comment]
I agree with adding a "reset layers" button. I don't think clicking on ZoLa will be clear enough for most users

**Comment by andycochran** [comment]
Okay, let's add a "Reset Layers" button to the bottom of the layer palette. 

For the "ZoLa" heading we can either: 
1. Remove the link so nothing happens when you click ZoLa
2. Close the content area when you click ZoLa, keeping all the filters as-is

Or we could do something more complex: 
- Make the default state of the app show the "About" content
- Clicking ZoLa shows you the "About" content
- Remove the "About" menu item

Not sure how that might work. Do we redirect `/` to `/about`? What's the route when the content area is closed? But I like the idea of having more of a landing page intro to the app.

**Comment by andycochran** [comment]
@allthesignals I've added a "Reset Map Layers" button (accidentally pushed it to `develop`). But it's nonfunctional. I'm gonna reassign this to you, 'cause I'm not certain how to make the button change the qps and not change the route. I'll move the "click ZoLa" stuff to its own issue so you can close this one once the button is rigged up.

**Comment by chriswhong** [comment]
+1 for not being able to click on ZoLa, for any reason, ever.

**Comment by chriswhong** [comment]
Taking a stab at clearing layers

**Comment by andycochran** [comment]
I'll nix the header link…

**Comment by andycochran** [comment]
Hotfix'd that in `develop` too. #YOLO

**Comment by andycochran** [comment]
@chriswhong Would be nice to add `disabled` to the button when clicked, or if the layers match the default.

**Comment by andycochran** [comment]
Closed by #197.
